
dizionarioFooter={"shop": {"af": "winkel", "sq": "dyqan", "am": "ሱቅ", "ar": "متجر", "hy": "խանութը", "az": "mağaza", "eu": "denda", "be": "крама", "bn": "দোকান", "bs": "prodavnica", "bg": "магазин", "ca": "botiga", "ceb": "shop", "ny": "malonda", "zh-cn": "店", "zh-tw": "店", "co": "negoziu", "hr": "dućan", "cs": "prodejna", "da": "butik", "nl": "winkel", "en": "shop", "eo": "butiko", "et": "poes", "tl": "mamili", "fi": "myymälä", "fr": "boutique", "fy": "winkel", "gl": "tenda", "ka": "მაღაზია", "de": "shop", "el": "κατάστημα", "gu": "દુકાન", "ht": "magazen", "ha": "shagon", "haw": "ke kūʻai kūʻai", "iw": "חנות", "hi": "दुकान", "hmn": "khw", "hu": "üzlet", "is": "verslun", "ig": "ụlọ ahịa", "id": "toko", "ga": "siopa", "it": "negozio", "ja": "ショップ", "jw": "toko", "kn": "ಅಂಗಡಿ", "kk": "дүкен", "km": "ហាង", "ko": "가게", "ku": "dikan", "ky": "дүкөн", "lo": "ຮ້ານຄ້າ", "la": "tabernam", "lv": "veikals", "lt": "parduotuvė", "lb": "Buttek", "mk": "продавница", "mg": "fivarotana", "ms": "kedai", "ml": "ഷോപ്പ്", "mt": "ħanut", "mi": "toa", "mr": "खरेदी", "mn": "дэлгүүр", "my": "ဆိုင်", "ne": "पसल", "no": "butikk", "ps": "هټۍ", "fa": "فروشگاه", "pl": "sklep", "pt": "fazer compras", "pa": "ਦੁਕਾਨ", "ro": "magazin", "ru": "магазин", "sm": "faleoloa", "gd": "bùth", "sr": "схоп", "st": "mabenkeleng", "sn": "shop", "sd": "دڪان", "si": "සාප්පුවක්", "sk": "predajňa", "sl": "trgovina", "so": "dukaanka", "es": "tienda", "su": "toko", "sw": "Duka", "sv": "affär", "tg": "коғаз", "ta": "கடை", "te": "షాప్", "th": "ร้านขายของ", "tr": "Dükkan", "uk": "магазин", "ur": "دکان", "uz": "do'kon", "vi": "shop", "cy": "siop", "xh": "ivenkile", "yi": "קראָם", "yo": "itaja", "zu": "esitolo", "fil": "mamili", "he": "נות" },
           "payment": {"af": "betaling","sq": "pagesë","am": "ክፍያ","ar": "دفع","hy": "վճարում","az": "ödəniş","eu": "ordainketa","be": "аплата","bn": "পারিশ্রমিক","bs": "plaćanje","bg": "плащане","ca": "pagament","ceb": "pagbayad","ny": "malipiro","zh-cn": "付款","zh-tw": "付款","co": "pagamento","hr": "plaćanje","cs": "platba","da": "betaling","nl": "betaling","en": "payment","eo": "pago","et": "makse","tl": "pagbabayad","fi": "maksu","fr": "Paiement","fy": "betelling","gl": "pagamento","ka": "გადახდა","de": "Zahlung","el": "πληρωμή","gu": "ચુકવણી","ht": "peman","ha": "biya","haw": "uku","iw": "תשלום","hi": "भुगतान","hmn": "them nqi","hu": "fizetés","is": "greiðslu","ig": "ịkwụ ụgwọ","id": "pembayaran","ga": "íocaíocht","it": "pagamento","ja": "支払い","jw": "pembayaran","kn": "ಪಾವತಿ","kk": "төлем","km": "ការទូទាត់","ko": "지불","ku": "diravdanî","ky": "төлөө","lo": "ການຊໍາລະເງິນ","la": "solucionis","lv": "maksājums","lt": "mokėjimo","lb": "Bezuelung","mk": "плаќање","mg": "fandoavam-bola","ms": "bayaran","ml": "പേയ്മെന്റ്","mt": "ħlas","mi": "utu","mr": "भरणा","mn": "төлбөр","my": "ငွေပေးချေမှု","ne": "भुक्तानी","no": "innbetaling","ps": "تادیه","fa": "پرداخت","pl": "Zapłata","pt": "Forma de pagamento","pa": "ਭੁਗਤਾਨ","ro": "plată","ru": "оплата","sm": "totogi","gd": "pàigheadh","sr": "плаћање","st": "tefo","sn": "kubhadhara","sd": "ادائيگي","si": "ගෙවීම","sk": "platba","sl": "plačila","so": "bixinta","es": "pago","su": "pamayaran","sw": "malipo","sv": "betalning","tg": "пардохт","ta": "கட்டணம்","te": "చెల్లింపు","th": "การชำระเงิน","tr": "ödeme","uk": "платіж","ur": "ادائیگی","uz": "to'lov","vi": "thanh toán","cy": "taliad","xh": "ntlawulo","yi": "צאָלונג","yo": "sisan","zu": "ukukhokha","fil": "pagbabayad","he": "תשלום"},
            "store": {"af": "winkel","sq": "dyqan","am": "ሱቅ","ar": "متجر","hy": "խանութը","az": "mağaza","eu": "denda","be": "крама","bn": "দোকান","bs": "dućan","bg": "магазин","ca": "botiga","ceb": "tindahan","ny": "sitolo","zh-cn": "商店","zh-tw": "商店","co": "store","hr": "dućan","cs": "obchod","da": "store","nl": "op te slaan","en": "store","eo": "vendejo","et": "salvestada","tl": "mag-imbak","fi": "myymälä","fr": "le magasin","fy": "winkel","gl": "tenda","ka": "მაღაზია","de": "Geschäft","el": "κατάστημα","gu": "દુકાન","ht": "magazen","ha": "adana","haw": "hale kūʻai","iw": "חנות","hi": "दुकान","hmn": "khw","hu": "bolt","is": "verslun","ig": "ụlọ ahịa","id": "toko","ga": "siopa","it": "negozio","ja": "格納","jw": "nyimpen","kn": "ಅಂಗಡಿ","kk": "дүкен","km": "ហាង","ko": "저장","ku": "dikan","ky": "дүкөн","lo": "store","la": "store","lv": "uzglabāt","lt": "saugoti","lb": "gespäichert","mk": "продавница","mg": "fivarotana","ms": "kedai","ml": "സംഭരിക്കുക","mt": "maħżen","mi": "toa","mr": "स्टोअर","mn": "дэлгүүр","my": "စတိုးဆိုင်","ne": "भण्डार","no": "store","ps": "زېرمه","fa": "فروشگاه","pl": "sklep","pt": "loja","pa": "ਸਟੋਰ","ro": "magazin","ru": "хранить","sm": "faleoloa","gd": "stòr","sr": "сторе","st": "boloka","sn": "store","sd": "اسٽور","si": "ගබඩාවකි","sk": "sklad","sl": "shranjevanje","so": "dukaanka","es": "almacenar","su": "toko","sw": "kuhifadhi","sv": "Lagra","tg": "захира кунед","ta": "கடை","te": "స్టోర్","th": "เก็บ","tr": "mağaza","uk": "магазин","ur": "اسٹور","uz": "saqlash","vi": "cửa hàng","cy": "siop","xh": "ivenkile","yi": "קראָם","yo": "itaja","zu": "esitolo","fil": "mag-imbak","he": "נות"},
            "buy": {"af": "koop","sq": "blej","am": "ግዛ","ar": "يشترى","hy": "գնել","az": "satın al","eu": "erosi","be": "купіць","bn": "কেনা","bs": "kupiti","bg": "Купува","ca": "comprar","ceb": "pagpalit","ny": "kugula","zh-cn": "购买","zh-tw": "購買","co": "cumprate","hr": "kupiti","cs": "Koupit","da": "købe","nl": "kopen","en": "buy","eo": "Aĉeti","et": "osta","tl": "bumili","fi": "ostaa","fr": "acheter","fy": "keapje","gl": "mercar","ka": "ყიდვა","de": "Kaufen","el": "αγορά","gu": "ખરીદી","ht": "achte","ha": "saya","haw": "kūʻai","iw": "לקנות","hi": "खरीद","hmn": "yuav","hu": "megvesz","is": "kaupa","ig": "zụta","id": "membeli","ga": "ceannaigh","it": "acquista","ja": "購入","jw": "tuku","kn": "ಖರೀದಿಸಿ","kk": "сатып алу","km": "ទិញ","ko": "사다","ku": "kirrîn","ky": "сатып алуу","lo": "ຊື້","la": "buy","lv": "nopirkt","lt": "pirkti","lb": "kafen","mk": "купи","mg": "mividy","ms": "beli","ml": "വാങ്ങാൻ","mt": "tixtri","mi": "hoko","mr": "खरेदी करा","mn": "худалдан авах","my": "မဝယ်","ne": "खरिद गर्नुहोस्","no": "kjøpe","ps": "پیرود","fa": "خرید","pl": "kupować","pt": "Comprar","pa": "ਖਰੀਦੋ","ro": "a cumpara","ru": "купить","sm": "faʻatau","gd": "ceannaich","sr": "буи","st": "reka","sn": "buy","sd": "خريد ڪيو","si": "මිලදී ගන්න","sk": "kúpiť","sl": "kupiti","so": "iibsato","es": "comprar","su": "meuli","sw": "kununua","sv": "köpa","tg": "харед","ta": "வாங்க","te": "కొనుగోలు","th": "ซื้อ","tr": "satın almak","uk": "купити","ur": "خریدنے","uz": "sotib oling","vi": "mua","cy": "prynu","xh": "ukuthenga","yi": "buy","yo": "ra","zu": "Thenga","fil": "bumili","he": "לקנות"},
            "delivery": {"af": "aflewering","sq": "dorëzim","am": "ማድረስ","ar": "توصيل","hy": "առաքում","az": "çatdırılma","eu": "entrega","be": "дастаўка","bn": "বিলি","bs": "dostava","bg": "доставка","ca": "lliurament","ceb": "delivery","ny": "kutumiza","zh-cn": "交货","zh-tw": "交貨","co": "consegna","hr": "dostava","cs": "dodávka","da": "levering","nl": "levering","en": "delivery","eo": "livero","et": "kohaletoimetamine","tl": "paghahatid","fi": "toimitus","fr": "livraison","fy": "befalling","gl": "entrega","ka": "მიწოდება","de": "Lieferung","el": "διανομή","gu": "ડિલિવરી","ht": "livrezon","ha": "bayarwa","haw": "hoʻouna","iw": "מסירה","hi": "वितरण","hmn": "yug","hu": "kézbesítés","is": "afhendingu","ig": "nnyefe","id": "pengiriman","ga": "seachadadh","it": "consegna","ja": "配達","jw": "pangiriman","kn": "ವಿತರಣೆ","kk": "жеткізу","km": "ការដឹកជញ្ជូន","ko": "배달","ku": "şandinî","ky": "жеткирүү","lo": "ການຈັດສົ່ງ","la": "partum","lv": "Piegāde","lt": "pristatymas","lb": "Liwwerung","mk": "испорака","mg": "fanaterana","ms": "penghantaran","ml": "ഡെലിവറി","mt": "kunsinna","mi": "tuku","mr": "वितरण","mn": "хүргэх","my": "ပို့ခြင်း","ne": "वितरण","no": "leveranse","ps": "انتقال","fa": "تحویل","pl": "dostawa","pt": "Entrega","pa": "ਡਿਲਿਵਰੀ","ro": "livrare","ru": "Доставка","sm": "tuʻuina atu","gd": "lìbhrigeadh","sr": "испорука","st": "ho romela","sn": "delivery","sd": "ترسيل","si": "බෙදාහැරීම","sk": "dodávka","sl": "dostavo","so": "bixinta","es": "entrega","su": "pangiriman","sw": "utoaji","sv": "leverans","tg": "фиристодан","ta": "விநியோக","te": "డెలివరీ","th": "การจัดส่ง","tr": "teslim","uk": "доставка","ur": "ترسیل","uz": "etkazib berish","vi": "chuyển","cy": "cyflwyno","xh": "ukuhanjiswa","yi": "עקספּרעס","yo": "ifijiṣẹ","zu": "ukulethwa","fil": "paghahatid","he": "מסירה"},
            "shipping": {"af": "gestuur","sq": "anijeve","am": "ማጓጓዣ","ar": "الشحن","hy": "առաքում","az": "Göndərmə","eu": "Bidalketa","be": "перавозка грузу","bn": "পাঠানো","bs": "shipping","bg": "доставка","ca": "Enviament","ceb": "pagpadala","ny": "Manyamulidwe","zh-cn": "运输","zh-tw": "運輸","co": "spedizione","hr": "dostava","cs": "Lodní doprava","da": "Forsendelse","nl": "Verzenden","en": "shipping","eo": "Sendo","et": "laevandus","tl": "Pagpapadala","fi": "laivaus","fr": "livraison","fy": "skipfeart","gl": "envío","ka": "ტრანსპორტირება","de": "Versand","el": "Αποστολή","gu": "વહાણ પરિવહન","ht": "anbake","ha": "shipping","haw": "ke kūʻai","iw": "משלוח","hi": "शिपिंग","hmn": "shipping","hu": "szállítás","is": "skipum","ig": "mbupu","id": "pengiriman","ga": "Á sheoladh","it": "spedizione","ja": "運送","jw": "shipping","kn": "ಹಡಗು","kk": "Жүк тасу","km": "ដឹកជញ្ជូន","ko": "배송","ku": "firotin","ky": "Жеткирүү","lo": "ການ​ຂົນ​ສົ່ງ","la": "naviportans","lv": "kuģniecība","lt": "laivyba","lb": "Liwwerung","mk": "Испорака","mg": "Fandefasana","ms": "penghantaran","ml": "ഷിപ്പിംഗ്","mt": "tbaħħir","mi": "kaipuke","mr": "शिपिंग","mn": "Тээвэрлэлт","my": "သင်္ဘောဖြင့်ကုန်ပစ္စည်းပို့ခြင်း","ne": "ढुवानी","no": "Shipping","ps": "لېږدول","fa": "حمل دریایی","pl": "Wysyłka ","pt": "Remessa","pa": "ਸ਼ਿਪਿੰਗ","ro": "livrare","ru": "Перевозка","sm": "felauaiga","gd": "luingearachd","sr": "поштарина","st": "Ho tsamaisa ka sekepe","sn": "kutumira","sd": "شپنگ","si": "නාවික","sk": "Doprava","sl": "Dostava","so": "maraakiibta","es": "Envío","su": "Balanja","sw": "meli","sv": "frakt","tg": "Фиристодан","ta": "கப்பல்","te": "షిప్పింగ్","th": "การส่งสินค้า","tr": "Nakliye","uk": "Доставка","ur": "شپنگ","uz": "yuk tashish; yetkazib berish","vi": "Đang chuyển hàng","cy": "llongau","xh": "Ukuhambisa ngenqanawe","yi": "שיפּינג","yo": "sowo","zu": "ukuthumela","fil": "Pagpapadala","he": "משלו"},
            "shopping": {"af": "Inkopies","sq": "pazar","am": "ግዢ","ar": "التسوق","hy": "գնումներ կատարելը","az": "alış-veriş","eu": "erosketak","be": "купля","bn": "কেনাকাটা","bs": "shopping","bg": "пазаруване","ca": "compres","ceb": "pagpamalit","ny": "kugula","zh-cn": "购物","zh-tw": "購物","co": "shopping","hr": "kupovina","cs": "nakupování","da": "handle ind","nl": "boodschappen doen","en": "shopping","eo": "butikumado","et": "sisseoste","tl": "shopping","fi": "ostokset","fr": "achats","fy": "winkeljen","gl": "facer compras","ka": "სავაჭრო","de": "Einkaufen","el": "ψώνια","gu": "શોપિંગ","ht": "fè makèt","ha": "cin kasuwa","haw": "kūʻai","iw": "קניות","hi": "खरीदारी","hmn": "khw","hu": "bevásárlás","is": "versla","ig": "ịzụ ahịa","id": "perbelanjaan","ga": "siopadóireacht","it": "shopping","ja": "ショッピング","jw": "belanja","kn": "ಶಾಪಿಂಗ್","kk": "сатып алу","km": "ទិញទំនិញ","ko": "쇼핑","ku": "kirînê","ky": "соода","lo": "shopping","la": "shopping","lv": "iepirkšanās","lt": "apsipirkti","lb": "Shopping","mk": "шопинг","mg": "fiantsenana","ms": "membeli belah","ml": "ഷോപ്പിംഗ്","mt": "xiri","mi": "hokohoko","mr": "खरेदी","mn": "дэлгүүр хэсэх","my": "စျေးဝယ်","ne": "खरीदारी","no": "kjøpesenter","ps": "پیرودنه","fa": "خريد كردن","pl": "zakupy","pt": "compras","pa": "ਖਰੀਦਦਾਰੀ","ro": "cumpărături","ru": "поход по магазинам","sm": "faatau","gd": "a ’ceannach","sr": "шопинг","st": "ho reka","sn": "shopping","sd": "خريداري","si": "සාප්පු සවාරි","sk": "nakupovanie","sl": "nakupovanje","so": "dukaamaysiga","es": "compras","su": "balanja","sw": "ununuzi","sv": "handla","tg": "харид","ta": "கடையில் பொருட்கள் வாங்குதல்","te": "షాపింగ్","th": "ช้อปปิ้ง","tr": "alışveriş yapmak","uk": "покупки","ur": "خریداری","uz": "xarid qilish","vi": "mua sắm","cy": "siopa","xh": "ukuthenga","yi": "שאַפּינג","yo": "ohun tio wa","zu": "bethenga","fil": "shopping","he": "קניות"},
            "credit card": {"af": "kredietkaart","sq": "kartë Krediti","am": "የዱቤ ካርድ","ar": "بطاقة الائتمان","hy": "ԿՐԵԴԻՏ քարտ","az": "kredit kartı","eu": "kreditu txartela","be": "крэдытная картка","bn": "ক্রেডিট কার্ড","bs": "kreditna kartica","bg": "кредитна карта","ca": "targeta de crèdit","ceb": "credit card","ny": "kiredi","zh-cn": "信用卡","zh-tw": "信用卡","co": "carta di creditu","hr": "kreditna kartica","cs": "kreditní karta","da": "kreditkort","nl": "kredietkaart","en": "credit card","eo": "kreditkarto","et": "krediitkaart","tl": "credit card","fi": "luottokortti","fr": "carte de crédit","fy": "Kredytkaart","gl": "tarxeta de crédito","ka": "საკრედიტო ბარათი","de": "Kreditkarte","el": "πιστωτική κάρτα","gu": "ક્રેડીટ કાર્ડ","ht": "kat kredi","ha": "katin bashi","haw": "kāleka kāki","iw": "כרטיס אשראי","hi": "क्रेडिट कार्ड","hmn": "credit card","hu": "hitelkártya","is": "kreditkort","ig": "kaadị akwụmụgwọ","id": "kartu kredit","ga": "cárta creidmheasa","it": "carta di credito","ja": "クレジットカード","jw": "kertu kredit","kn": "ಕ್ರೆಡಿಟ್ ಕಾರ್ಡ್","kk": "несие картасы","km": "កាត​ឥណទាន","ko": "신용 카드","ku": "li kû çûn","ky": "кредиттик карта","lo": "ບັດ​ເຄຣ​ດິດ","la": "fidem card","lv": "kredītkarte","lt": "kredito kortele","lb": "Kreditkaart","mk": "кредитна картичка","mg": "carte de crédit","ms": "kad kredit","ml": "ക്രെഡിറ്റ് കാർഡ്","mt": "karta tal-kreditu","mi": "kāri nama","mr": "क्रेडीट कार्ड","mn": "кредит карт","my": "အကြွေးဝယ်ကဒ်","ne": "क्रेडिट कार्ड","no": "kredittkort","ps": "باور كارت","fa": "کارت اعتباری","pl": "karta kredytowa","pt": "cartão de crédito","pa": "ਕਰੇਡਿਟ ਕਾਰਡ","ro": "card de credit","ru": "кредитная карта","sm": "numera tala tupe","gd": "Cairt creideis","sr": "кредитна картица","st": "karete ea mokitlane","sn": "kadhi rechikwereti","sd": "ڪريڊٽ ڪارڊ","si": "ණයවර පත","sk": "kreditná karta","sl": "kreditno kartico","so": "kaarka deynta","es": "tarjeta de crédito","su": "kartu kiridit","sw": "kadi ya mkopo","sv": "kreditkort","tg": "корти кредитӣ","ta": "கடன் அட்டை","te": "క్రెడిట్ కార్డు","th": "บัตรเครดิต","tr": "kredi kartı","uk": "кредитна карта","ur": "کریڈٹ کارڈ","uz": "kredit karta","vi": "thẻ tín dụng","cy": "cerdyn credyd","xh": "ikhadi letyala","yi": "קרעדיט קארטל","yo": "Kaddi kirediti","zu": "ikhadi lesikweletu","fil": "credit card","he": "כרטיס אשראי"}
            }

# for key in dizionarioFooter:
#     print("---------"+key+"----------")
#     for el in dizionarioFooter[key]:
#         print(el)
#         print(dizionarioFooter[key].get(el))















